stunnel-5.44

diff --git a/tests/make_test b/tests/make_test
--- a/tests/make_test
+++ b/tests/make_test
@@ -11,7 +11,16 @@ script_path=$(pwd)
 cd "${result_path}"
 result_path="${result_path}/logs"
 
-if [ -n "$(command -v ncat)" ] || [ -n "$(command -v nc)" ]
+if [ -n "$(command -v ncat)" ]
+  then # ncat
+    mynetcat="ncat"
+  elif [ -n "$(command -v nc)" ]
+    then # nc
+      mynetcat="nc"
+  else # # netcat not found
+    mynetcat="null"
+  fi
+if [ "$mynetcat" != "null" ] # netcat is required
   then
     rm -rf "${result_path}"
     mkdir "${result_path}"
@@ -19,40 +28,32 @@ if [ -n "$(command -v ncat)" ] || [ -n "$(command -v nc)" ]
     date > "results.log"
     ../../src/stunnel -version 2>> "results.log"
     printf "\n%s\n" "Testing..." >> "results.log"
-    if ! grep -q "apple" "results.log"
-      then
-        head -n5 "results.log"
-        for plik in ${script_path}/recipes/*
-          do
-            /bin/sh $plik
-            state=$?
-            if [ "$state" -eq 0 ]
-              then
-                count=$((count + 1))
-              elif [ "$state" -eq 125 ]
-                then
-                  skip=$((skip + 1))
-              else # $state -eq 1
-                fail=$((fail + 1))
-                result=1
-              fi
-          done
-        if [ $count -eq 0 ]
-          then # no test was done
+    head -n5 "results.log"
+    for plik in ${script_path}/recipes/*
+      do
+        /bin/sh $plik $mynetcat
+        state=$?
+        if [ "$state" -eq 0 ]
+          then # $state=0
+            count=$((count + 1))
+          elif [ "$state" -eq 125 ]
+            then # $state=125
+              skip=$((skip + 1))
+          else # $state=1
+            fail=$((fail + 1))
             result=1
           fi
-        printf "%s\n" "summary: success $count, skip $skip, fail $fail"
-        printf "%s\n" "summary: success $count, skip $skip, fail $fail" >> "results.log"
-        printf "%s\n" "./make_test finished"
-      else # macOS
-        head -n2 "results.log" | tail -1
-        printf "%s\n" "./make_test error: platform not supported"
-        printf "%s\n" "./make_test error: platform not supported" >> "results.log"
-        result=125
+      done
+    if [ $count -eq 0 ]
+      then # no test was done
+        result=1
       fi
+    printf "%s\n" "summary: success $count, skip $skip, fail $fail"
+    printf "%s\n" "summary: success $count, skip $skip, fail $fail" >> "results.log"
+    printf "%s\n" "./make_test finished"
     cd ..
-  else # ncat was not found
-    printf "%s\n" "./make_test error: ncat (nc) not found in \$PATH"
-    result=125
+  else # netcat not found
+    printf "%s\n" "./make_test skipped: ncat (nc) not found in \$PATH"
+    #result=125
   fi
 exit $result
diff --git a/tests/test_library b/tests/test_library
--- a/tests/test_library
+++ b/tests/test_library
@@ -5,30 +5,49 @@ cd $(dirname "$0")/../
 script_path=$(pwd)
 cd "${result_path}"
 
-screen_result() {
-  printf "%-35s\t%s\n" "test $1" "$2"
-  if [ "$2" = "failed" ]
+result_logs() {
+  # $1 = test name
+  # $2 = status: "ok" / "failed" / "configuration failed" / "expected error"
+  #              "skipped" / "ncat (nc) failed" / "shouldn't work"
+  # $3 = file name: "stunnel" / "error"
+
+  if [ "$2" = "expected error" ]
+    then # expected error - it's ok
+      printf "%-35s\t%s\n" "test $1" "ok"
+     else
+      printf "%-35s\t%s\n" "test $1" "$2"
+     fi
+  if [ "$2" != "ok" ] && [ "$2" != "ncat (nc) failed" ]
+    then
+      printf "%-35s\t%s\n" "test $1" "$2" >> "results.log"
+    fi
+  if [ "$2" = "failed" ] || [ "$2" = "configuration failed" ] || [ "$2" = "shouldn't work" ]
     then # file with stunnel error logs
       printf "%-35s\t%s\n" "error logs" "logs/$1.log"
-    fi
-  return 0
-}
-
-file_result() {
-  if [ -s "$2.log" ] && [ "$3" != "expected error" ]
-    then # $2 = "stunnel" / "error"
-      cat "$2.log" > "$1.log"
-    fi
-  if [ "$3" = "skipped" ]
-    then
-      printf "%-35s\t%s\n" "test $1" "$3" >> "results.log"
+      cat "$3.log" > "$1.log"
     else
-      printf "%-35s\t%s\n" "test $1" "$3" > "temp.log"
+      cat "temp.log" >> "results.log" 2>> "stderr_nc.log"
     fi
   return 0
 }
 
-clean_logs(){
+exit_logs() {
+  # $1 = test name
+  # $2 = status
+
+  case "$2" in
+    "ok") result_logs "$1" "ok" "UNUSED PATTERN";;
+    "failed") result_logs "$1" "failed" "stunnel";;
+    "configuration failed") result_logs "$1" "configuration failed" "error";;
+    "expected error") result_logs "$1" "expected error" "UNUSED PATTERN";;
+    "skipped") result_logs "$1" "skipped" "error";;
+    "ncat (nc) failed") result_logs "$1" "failed" "stunnel";;
+    "shouldn't work") result_logs "$1" "shouldn't work" "stunnel";;
+  esac
+  return 0
+}
+
+clean_logs() {
   rm -f "stunnel.log"
   rm -f "temp.log"
   rm -f "error.log"
@@ -37,9 +56,11 @@ clean_logs(){
   return 0
 }
 
-waiting_for(){
+waiting_for() {
+  # waiting for strings ($2 or $3 or $4) to appear in the file $1.log
+
   mkfifo "fifo"
-  (cat "$1.log"; tail -f "$1.log") > "fifo" &
+  (cat "$1.log"; tail -f "$1.log") > "fifo" 2>> "stderr_nc.log" &
   pid_tail=$!
   (sleep 3; echo "TIMEOUT") > "fifo" &
   pid_timeout=$!
@@ -47,204 +68,229 @@ waiting_for(){
   pid_children=$(ps -o pid,ppid | \
     awk -v ppid1="${pid_tail}" -v ppid2="${pid_timeout}" \
       '{if ($2==ppid1 || $2==ppid2) print $1}')
-  kill ${pid_tail} ${pid_timeout} ${pid_children}
-  wait ${pid_tail} ${pid_timeout}
+  kill ${pid_tail} ${pid_timeout} ${pid_children} 2>> "stderr_nc.log"
+  wait ${pid_tail} ${pid_timeout} 2>> "stderr_nc.log"
   rm -f "fifo"
+  return 0
 }
 
-connecting_ncat(){
+connecting_ncat() {
+  # $1 = test name
+  # $2 = string to send
+  # $3 = netcat name: "ncat" / "nc"
+
   result=0
-  rm -f "stderr_nc.log"
+  mkfifo "nodata"
   printf "\n%s\n" "test $1" > "stderr_nc.log"
-  ncat -l -p "$http2" -vvv > "temp.log" 2>> "stderr_nc.log" &
-  pid_ncat=$!
-  waiting_for "stderr_nc" "Listening" "QUITTING" "ncat\: not found" "UNUSED PATTERN"
-  if grep -q "Listening" "stderr_nc.log"
-    then # Listening
-      printf "%-35s\t%s\n" "test $1" "$2" | ncat 127.0.0.1 "$http1" -vv 2>> "stderr_nc.log"
-    else # QUITTING - retry with nc
-      cat "stderr_nc.log" >> "stderr.log"
-      rm -f "stderr_nc.log"
-      printf "\n%s\n" "test $1" > "stderr_nc.log"
-      nc -l -p "$http2" -vvv > "temp.log" 2>> "stderr_nc.log" &
-      pid_nc=$!
-      waiting_for "stderr_nc" "Listening" "listening" "QUITTING"
-      if grep -q "istening" "stderr_nc.log"
-        then # Listening or listening
-          printf "%-35s\t%s\n" "test $1" "$2" | nc 127.0.0.1 "$http1" -vv 2>> "stderr_nc.log" &
-        else # ncat (nc) failed
-          result=1
+  cat "nodata" | "$3" -l -p "$http2" -vvv >"temp.log" 2>> "stderr_nc.log" &
+  pid_nc=$!
+  waiting_for "stderr_nc" "Listening" "listening" "QUITTING"
+  if grep -q "istening" "stderr_nc.log"
+    then # Listening or listening
+      if [ "$3" = "ncat" ]
+        then
+          printf "%-35s\t%s\n" "test $1" "$2" | "$3" 127.0.0.1 "$http1" -vv 2>> "stderr_nc.log"
+        else
+          printf "%-35s\t%s\n" "test $1" "$2" | "$3" 127.0.0.1 "$http1" -vv 2>> "stderr_nc.log" &
         fi
+    else # ncat (nc) failed
+      result=1
     fi
-  if [ -n "$(command -v ncat)" ]
+  if [  "$3" = ncat ]
     then
       waiting_for "stderr_nc" "Closing" "Connection reset by peer" "UNUSED PATTERN"
     else
-      waiting_for "stderr_nc" "succeeded" "from localhost" "Connection reset by peer"
+      waiting_for "stderr_nc" "accepted" "from localhost" "Connection reset by peer"
   fi
-  kill -TERM ${pid_ncat} ${pid_nc} 2>> "stderr_nc.log"
+  kill -TERM ${pid_nc} 2>> "stderr_nc.log"
   cat "stderr_nc.log" >> "stderr.log"
+  echo "somedata" > "nodata"
+  rm -f "nodata"
   return $result
 }
 
 killing_stunnel() {
-  waiting_for "stunnel" "Service .* finished" "UNUSED PATTERN" "UNUSED PATTERN" "UNUSED PATTERN"
-  kill -TERM $(tail "stunnel.pid")
+  waiting_for "$1" "Service .* finished" "Sent socket write shutdown" "UNUSED PATTERN"
+  kill -TERM $(tail "stunnel.pid") 2>> "stderr.log"
+  waiting_for "stunnel" "removing pid file" "UNUSED PATTERN" "UNUSED PATTERN"
   return 0
 }
 
 reload_stunnel() {
-  while [ ! -e "stunnel.pid" ]
-    do
-      sleep 1
-    done
-  kill -HUP $(tail "stunnel.pid") 2>> "stderr_nc.log"
+  waiting_for "stunnel" "stunnel.pid" "UNUSED PATTERN" "UNUSED PATTERN"
+  kill -HUP $(tail "stunnel.pid") 2>> "stderr.log"
+  waiting_for "stunnel" "127.0.0.1:${http1}" "UNUSED PATTERN" "UNUSED PATTERN"
   return 0
 }
 
 expected_success() {
+  # expects to send the s using stunnel
+  # $1 = test name
+  # $2 = netcat name: "ncat" / "nc"
+
   result=0
   if [ ! -s "error.log" ]
     then
-      if connecting_ncat "$1" "success"
+      if connecting_ncat "$1" "success" "$2"
         then
-          killing_stunnel
           if grep -q "test $1.*success" "temp.log"
             then
-              screen_result "$1" "ok"
+              exit_code="ok"
             else # test failed
-              file_result "$1" "stunnel" "failed"
-              screen_result "$1" "failed"
+              exit_code="failed"
               result=1
             fi
         else # ncat (nc) failed
-          killing_stunnel
-          screen_result "$1" "ncat (nc) failed"
+          exit_code="ncat (nc) failed"
           result=1
         fi
+      killing_stunnel stunnel
     else # configuration failed
-      file_result "$1" "error" "configuration failed"
-      screen_result "$1" "configuration failed"
+      exit_code="configuration failed"
       result=1
     fi
+  exit_logs "$1" "$exit_code"
   return $result
 }
 
 expected_failure() {
+  # $1 = test name
+  # $2 = netcat name: "ncat" / "nc"
+
   result=0
   if [ ! -s "error.log" ]
     then
-      if connecting_ncat "$1" "shouldn't work"
+      if connecting_ncat "$1" "shouldn't work" "$2"
         then
-          killing_stunnel
           if grep -q "test $1.*shouldn't work" "temp.log"
             then # ops...stunnel works
-              screen_result "$1" "shouldn't work"
+              exit_code="shouldn't work"
               result=1
             else
-              file_result "$1" "stunnel" "expected error"
-              screen_result "$1" "ok"
+              exit_code="expected error"
             fi
         else # ncat (nc) failed
-          killing_stunnel
-          screen_result "$1" "ncat (nc) failed"
+          exit_code="ncat (nc) failed"
           result=1
         fi
+      killing_stunnel stunnel
     else # configuration failed, but it is ok
-      file_result "$1" "error" "expected error"
-      screen_result "$1" "ok"
+      exit_code="expected error"
     fi
+  exit_logs "$1" "$exit_code"
   return $result
 }
 
 execute_program() {
+  # $1 = test name
+  # $2 = netcat name: "ncat" / "nc"
+
   result=0
+  mkfifo "nodata"
   if [ ! -s "error.log" ]
     then
-      nc 127.0.0.1 "$http1" -vv > "temp.log" 2>>"stderr.log" &
-      killing_stunnel
+      cat "nodata" | "$2" 127.0.0.1 "$http1" -vv > "temp.log" 2>>"stderr.log" &
+      pid_nce=$!
+      killing_stunnel stunnel
+      kill -TERM ${pid_nce} 2>> "stderr.log"
+      echo "somedata" > "nodata" 2>> "stderr.log"
+      rm -f "nodata"
       if grep -q "test $1.*success" "temp.log"
         then
           if grep -q "$1_error" "temp.log"
             then # only for redirect tests
-              file_result "$1" "stunnel" "failed"
-              screen_result "$1" "failed"
+              exit_code="failed"
               result=1
             else
-              screen_result "$1" "ok"
+              exit_code="ok"
           fi
         else # test failed
-          file_result "$1" "stunnel" "failed"
-          screen_result "$1" "failed"
+          exit_code="failed"
           result=1
         fi
     else # configuration failed
-      file_result "$1" "error" "configuration failed"
-      screen_result "$1" "configuration failed"
+      exit_code="configuration failed"
       result=1
     fi
-  return $result
-}
-
-check_prio(){
-  result=0
-  if [ $1 = "037_failover_prio1" ]
-    then
-      serv="server_2\] accepted connection"
-    else
-      serv="server_1\] accepted connection"
-    fi
-  if ! grep -q "$serv" "stunnel.log"
-    then # second server doesn't accept any client
-      if [ $2 -eq $3 ]
-        then # last successed turn of the loop
-          printf "%-35s\t%s\n" "test $1" "success" > "temp.log"
-          screen_result "$1" "ok"
-        fi
-    else # error - second server accepts a client
-        file_result "$1" "stunnel" "failed"
-        screen_result "$1" "failed"
-        result=1
-    fi
+  exit_logs "$1" "$exit_code"
   return $result
 }
 
 loop_prio() {
+  # $1 = test name
+  # $2 = netcat name: "ncat" / "nc"
+
   result=0
   i=1
   max=12
   start $i 2> "error.log"
   if [ ! -s "error.log" ]
     then
+      waiting_for "stunnel" "Created pid file" "UNUSED PATTERN" "UNUSED PATTERN"
+      mv "stunnel.log" "stunnel_0.log"
+      kill -USR1 $(tail "stunnel.pid") 2>> "stderr.log"
       while [ $i -le $max ] && [ $result -eq 0 ]
         do
-          if connecting_ncat "$1" "success"
+          if connecting_ncat "$1" "success" "$2"
             then
+              waiting_for "stunnel" "Service .* finished" "Sent socket write shutdown" "UNUSED PATTERN"
               if grep -q "test $1.*success" "temp.log"
                 then
-                  check_prio "$1" "$i" "$max"
-                  result=$?
+                  if [ $1 = "037_failover_prio1" ]
+                    then
+                      serv="server_2\] accepted connection"
+                    else
+                      serv="server_1\] accepted connection"
+                    fi
+		  if ! grep -q "$serv" "stunnel.log"
+		    then # second server doesn't accept any client
+		      if [ $i -eq $max ]
+			then # last successed turn of the loop
+			  exit_code="ok"
+			fi
+		    else # error - second server accepts a client
+                      exit_code="failed"
+		      result=1
+		    fi
                 else # stunnel doesn't work
-                  file_result "$1" "stunnel" "failed"
-                  screen_result "$1" "failed"
+                  exit_code="failed"
                   result=1
                 fi
             else # ncat (nc) failed
-              screen_result "$1" "ncat (nc) failed"
+              exit_code="ncat (nc) failed"
               result=1
             fi
+          waiting_for "stunnel" "Service .* finished" "Sent socket write shutdown" "UNUSED PATTERN"
+          mv "stunnel.log" "stunnel_$i.log"
+          kill -USR1 $(tail "stunnel.pid") 2>> "stderr.log"
           i=$((i + 1))
         done
-      killing_stunnel
+      cat "stunnel_0.log" > "stunnel_all.log"
+      rm -f "stunnel_0.log"
+      j=1
+      while [ $j -lt $i ]
+        do
+          printf "%s\n" "connection $j" >> "stunnel_all.log"
+          cat "stunnel_$j.log" >> "stunnel_all.log"
+          rm -f "stunnel_$j.log"
+          j=$((j + 1))
+        done
+      killing_stunnel stunnel_all
+      cat "stunnel.log" >> "stunnel_all.log"
+      cat "stunnel_all.log" > "stunnel.log"
+      rm -f "stunnel_all.log"
     else # configuration failed
-      file_result "$1" "error" "configuration failed"
-      screen_result "$1" "configuration failed"
+      exit_code="configuration failed"
       result=1
     fi
+  exit_logs "$1" "$exit_code"
   return $result
 }
 
 loop_rr() {
+  # $1 = test name
+  # $2 = netcat name: "ncat" / "nc"
+
   result=0
   i=1
   max=3
@@ -254,63 +300,79 @@ loop_rr() {
   start $i 2> "error.log"
   if [ ! -s "error.log" ]
     then
+      waiting_for "stunnel" "Created pid file" "UNUSED PATTERN" "UNUSED PATTERN"
+      mv "stunnel.log" "stunnel_0.log"
+      kill -USR1 $(tail "stunnel.pid") 2>> "stderr.log"
       while [ $i -le $max ] && [ $result -eq 0 ]
         do
-          if connecting_ncat "$1" "success"
+          if connecting_ncat "$1" "success" "$2"
             then
+              waiting_for "stunnel" "Service .* finished" "Sent socket write shutdown" "UNUSED PATTERN"
               if ! grep -q "test $1.*success" "temp.log"
                 then # stunnel doesn't work
-                  file_result "$1" "stunnel" "failed"
-                  screen_result "$1" "failed"
+                  exit_code="failed"
                   result=1
                 fi
             else # ncat (nc) failed
-              screen_result "$1" "ncat (nc) failed"
+              exit_code="ncat (nc) failed"
               result=1
             fi
-
+          waiting_for "stunnel" "Service .* finished" "Sent socket write shutdown" "UNUSED PATTERN"
+          mv "stunnel.log" "stunnel_$i.log"
+          kill -USR1 $(tail "stunnel.pid") 2>> "stderr.log"
           i=$((i + 1))
         done
+      cat "stunnel_0.log" > "stunnel_all.log"
+      rm -f "stunnel_0.log"
+      j=1
+      while [ $j -lt $i ]
+        do
+          printf "%s\n" "connection $j" >> "stunnel_all.log"
+          cat "stunnel_$j.log" >> "stunnel_all.log"
+          rm -f "stunnel_$j.log"
+          j=$((j + 1))
+        done
+      killing_stunnel stunnel_all
+      cat "stunnel.log" >> "stunnel_all.log"
+      cat "stunnel_all.log" > "stunnel.log"
+      rm -f "stunnel_all.log"
       first=$(grep -c "server_1\] accepted connection" "stunnel.log")
       second=$(grep -c "server_2\] accepted connection" "stunnel.log")
       third=$(grep -c "server_3\] accepted connection" "stunnel.log")
-      killing_stunnel
     else # configuration failed
-      file_result "$1" "error" "configuration failed"
-      screen_result "$1" "configuration failed"
+      exit_code="configuration failed"
       result=1
     fi
-    if [ $result -eq 0 ] && [ -e "stunnel.log" ]
-      then
-        file_result "$1" "stunnel" "success"
-      fi
     if [ $result -eq 0 ]
       then
         product=$((first * second * third))
         if [ $product -ne 0 ]
           then # round robin
             printf "%-35s\t%s\n" "test $1: $first x $second x $third" "success" > "temp.log"
-            screen_result "$1" "ok"
-            rm "$1.log"
+            exit_code="ok"
           else
             printf "%-35s\t%s\n" "test $1: $first x $second x $third" "failed" > "temp.log"
-            screen_result "$1" "failed"
+            exit_code="failed"
             result=1
           fi
       fi
+  exit_logs "$1" "$exit_code"
   return $result
 }
 
 test_log_for() {
+  # $1 = test name
+  # $2 = function name
+  # $3 = netcat name: "ncat" / "nc"
+
   case "$2" in
-    "success") expected_success "$1";;
-    "failure") expected_failure "$1";;
-    "execute") execute_program "$1";;
-    "prio") loop_prio "$1";;
-    "rr") loop_rr "$1";;
+    "success") expected_success "$1" "$3";;
+    "failure") expected_failure "$1" "$3";;
+    "execute") execute_program "$1" "$3";;
+    "prio") loop_prio "$1" "$3";;
+    "rr") loop_rr "$1" "$3";;
   esac
   result=$?
-  cat "temp.log" >> "results.log"
   clean_logs
   return $result
 }
