stunnel-5.56

diff --git a/tests/test_library b/tests/test_library
--- a/tests/test_library
+++ b/tests/test_library
@@ -693,14 +693,13 @@ two_instances() {
   local result=0
   local i=0
   local j=0
-  start_stunnel "$1"
+  start_server 2> "error.log"
   if no_file "error.log"
     then
-      waiting_for "stunnel" "Created pid file"
-      start_server 2> "error.log"
+      waiting_for "stunnel_server" "Created pid file"
+      start_stunnel "$1"
       if no_file "error.log"
         then
-          waiting_for "stunnel_server" "Created pid file"
           while [ $i -le 2 ]
             do
               i=$(grep -c "Retrying an exec+connect section" "stunnel.log")
@@ -709,22 +708,21 @@ two_instances() {
             then
               result=1
             fi
-          cat stunnel_server.log >> "stunnel.log"
+          mv "stunnel_server.log" "stunnel_all.log"
           start_server 2>> "error.log"
-          waiting_for "stunnel_server" "Created pid file"
-          while [ $i -le 3 ]
-            do
-              i=$(grep -c "Retrying an exec+connect section" "stunnel.log")
-            done
+          waiting_for "stunnel_server" "Service .* finished"
           if ! killing_stunnel stunnel_server
             then
               result=1
             fi
-          cat stunnel_server.log >> "stunnel.log"
+          cat "stunnel_server.log" >> "stunnel_all.log"
           if ! killing_stunnel stunnel
             then
               result=1
             fi
+          cat "stunnel.log" >> "stunnel_all.log"
+          cat "stunnel_all.log" > "stunnel.log"
+          rm -f "stunnel_all.log"
           if [ $result -eq 0 ]
             then
               finding_text "yes" "test $1.*success" "temp.log" "UNUSED PATTERN"
@@ -736,12 +734,13 @@ two_instances() {
               exit_code="failed"
               result=1
             fi
-        else # server configuration failed
-          killing_stunnel stunnel
+        else # client configuration failed
+          killing_stunnel stunnel_server
           exit_code="configuration failed"
           result=1
         fi
-    else # client configuration failed
+    else # server configuration failed
+      cat "stunnel_server.log" >> "stunnel.log"
       result=1
     fi
   if ! finding_text "no" "INTERNAL ERROR" "stunnel.log" "error.log"
@@ -749,6 +748,49 @@ two_instances() {
       result=1
     fi
   rm -f "stunnel_server.log"
+  exit_logs "$1" "$exit_code"
+  return $result
+}
+
+resumption() {
+  # $1 = test name
+  # $2 = number of new connections
+
+  local result=0
+  local i=0
+  local j=0
+  check_ports "$1"
+  start_stunnel "$1"
+  if no_file "error.log"
+    then
+      waiting_for "stunnel" "Service .* finished"
+      connecting_ncat "$1" "success"
+      while [ $i -le $2 ]
+        do
+          i=$(grep -c "Retrying an exec+connect section" "stunnel.log")
+        done
+      if ! killing_stunnel stunnel
+        then
+          result=1
+        fi
+      if [ $result -eq 0 ]
+        then
+          finding_text "yes" "test $1.*success" "temp.log" "UNUSED PATTERN"
+          result=$?
+        fi
+      j=$(grep -c "accepted: new session negotiated" "stunnel.log")
+      if [ $result -eq 0 ] && [ $j -ne $2 ]
+        then
+          exit_code="failed"
+          result=1
+        fi
+    else # configuration failed
+      result=1
+    fi
+  if ! finding_text "no" "INTERNAL ERROR" "stunnel.log" "error.log"
+    then
+      result=1
+    fi
   exit_logs "$1" "$exit_code"
   return $result
 }
@@ -792,6 +834,7 @@ test_log_for() {
     "rr") loop_rr "$1";;
     "session") loop_session "$1" "$3";;
     "instances") two_instances "$1" "$3";;
+    "resumption") resumption "$1" "$3";;
   esac
   result=$?
   clean_logs
